// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KanbanBackend.Migrations
{
    [DbContext(typeof(KanbanDbContext))]
    partial class KanbanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Board", b =>
                {
                    b.Property<string>("BoardId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Title");

                    b.HasKey("BoardId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Card", b =>
                {
                    b.Property<string>("CardId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("KanbanListId");

                    b.Property<string>("Text");

                    b.HasKey("CardId");

                    b.HasIndex("KanbanListId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("KanbanList", b =>
                {
                    b.Property<string>("KanbanListId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BoardId");

                    b.Property<string>("Title");

                    b.HasKey("KanbanListId");

                    b.HasIndex("BoardId");

                    b.ToTable("Lists");
                });

            modelBuilder.Entity("Card", b =>
                {
                    b.HasOne("KanbanList")
                        .WithMany("Cards")
                        .HasForeignKey("KanbanListId");
                });

            modelBuilder.Entity("KanbanList", b =>
                {
                    b.HasOne("Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardId");
                });
#pragma warning restore 612, 618
        }
    }
}
